In [1]:
import numpy as np

In [2]:
a = [1,2,3]
b = [4,5,6]
c = a + b
c

[1, 2, 3, 4, 5, 6]

In [3]:
b = np.array(b)
c = a + b
c

array([5, 7, 9])

In [4]:
# calculate dividends
dividends = [1,1.5,1.75, 0.75, 1.25]
stock_prices = [50, 55, 62, 47, 84]


np_dividends = np.array(dividends)
np_stock_prices = np.array(stock_prices)
np_stock_prices

array([50, 55, 62, 47, 84])

In [5]:
dividend_yield = np_dividends/np_stock_prices*100
dividend_yield

array([ 2.        ,  2.72727273,  2.82258065,  1.59574468,  1.48809524])

In [6]:
dividend_yield[1]

2.7272727272727271

In [7]:
dividend_yield > 2.72

array([False,  True,  True, False, False], dtype=bool)

In [8]:
dividend_yield[dividend_yield > 2.72]

array([ 2.72727273,  2.82258065])

In [10]:
np_2d = np.array([[1,1.5,1.75, 0.75, 1.25], [50, 55, 62, 47, 84]])
np_2d

array([[  1.  ,   1.5 ,   1.75,   0.75,   1.25],
       [ 50.  ,  55.  ,  62.  ,  47.  ,  84.  ]])

In [11]:
np_2d.shape

(2, 5)

In [13]:
# in 2d array i returns row
np_2d[1]

array([ 50.,  55.,  62.,  47.,  84.])

In [15]:
np_2d.resize((5,2))
np_2d

array([[  1.  ,   1.5 ],
       [  1.75,   0.75],
       [  1.25,  50.  ],
       [ 55.  ,  62.  ],
       [ 47.  ,  84.  ]])

In [16]:
np_2d[1][1]

0.75

In [17]:
np_2d[1,1]

0.75

In [18]:
np_2d[1,:]

array([ 1.75,  0.75])

In [19]:
np_2d[1:3]

array([[  1.75,   0.75],
       [  1.25,  50.  ]])

In [20]:
np_2d.resize((2,5))
np_2d

array([[  1.  ,   1.5 ,   1.75,   0.75,   1.25],
       [ 50.  ,  55.  ,  62.  ,  47.  ,  84.  ]])

In [21]:
average_stock_price = np.mean(np_2d[1,:])
average_stock_price

59.600000000000001

In [22]:
sd = np.std(np_2d[1,:])
sd

13.215142829345433

In [24]:
#sum
s = np.sum(np_2d[1,:])
s

298.0

In [26]:
prices = np.round(np.random.normal(50,.20, 10), 2)
prices

array([ 50.17,  49.72,  50.11,  50.  ,  49.89,  49.71,  50.07,  49.84,
        49.76,  50.05])

In [27]:
dividends= np.round(np.random.normal(50,.20, 10), 2)
dividends

array([ 50.2 ,  49.89,  50.06,  50.15,  49.94,  49.95,  49.71,  49.89,
        49.91,  50.  ])